CREATE TABLE "categorias" (
  "id_categoria" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "descripcion" text
);

CREATE TABLE "proveedores" (
  "id_proveedor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_empresa" varchar(150) NOT NULL,
  "nombre_contacto" varchar(100),
  "telefono" varchar(20),
  "correo" varchar(100)
);

CREATE TABLE "productos" (
  "id_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_sku" varchar(50) UNIQUE,
  "nombre" varchar(150) NOT NULL,
  "descripcion" text,
  "precio_compra" decimal(10,2),
  "precio_venta" decimal(10,2),
  "stock_actual" int DEFAULT 0,
  "stock_minimo" int DEFAULT 5,
  "id_categoria" int,
  "id_proveedor" int
);

CREATE TABLE "movimientos" (
  "id_movimiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int,
  "tipo_movimiento" varchar(20),
  "cantidad" int NOT NULL,
  "fecha_hora" TIMESTAMP DEFAULT now(),
  "motivo" varchar(150)
);

COMMENT ON COLUMN "productos"."codigo_sku" IS 'código de barras o identificador comercial';

COMMENT ON COLUMN "productos"."stock_actual" IS 'cantidad disponible';

COMMENT ON COLUMN "productos"."stock_minimo" IS 'alerta de reabastecimiento';

COMMENT ON COLUMN "movimientos"."tipo_movimiento" IS 'puede ser ''entrada'' o ''salida''';

COMMENT ON COLUMN "movimientos"."motivo" IS 'ej. ''venta'', ''compra'', ''devolución''';

ALTER TABLE "productos" ADD FOREIGN KEY ("id_categoria") REFERENCES "categorias" ("id_categoria") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "productos" ADD FOREIGN KEY ("id_proveedor") REFERENCES "proveedores" ("id_proveedor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimientos" ADD FOREIGN KEY ("id_producto") REFERENCES "productos" ("id_producto") DEFERRABLE INITIALLY IMMEDIATE;
